### ISSUE TITLE
Retry download fails with Error: 500

### ISSUE THREAD

**Issue by rotanigroc** [alexta69/metube#233]
I attempted to download a long playlist and ~30% timed out. When I went to retry individual videos using the `rotate-right` button it gives a popup saying:
```
Error adding URL: 500 Internal Server Error

Server got itself in trouble
```

Looking in the logs, it appears to be sending the request with the folder name in the `format` field

```
INFO:aiohttp.access:<-TrimmedClientIP-> [09/Mar/2023:00:49:45 +0000] "GET /download/DBZAbridged/TeamFourStar%2FDragon%20Ball%20Z%20Abridged%EF%BC%9A%20Plan%20to%20Eradicate%20Christmas%20-%20Team%20Four%20Star%20(TFS).f140.m4a HTTP/1.1"

<-Trimmed Unrelated Lines->

INFO:ytdl:adding https://www.youtube.com/watch?v=2zOv7kvYmtg: quality='best' format='DBZAbridged' already=None folder=None
INFO:aiohttp.access:<-TrimmedClientIP-> [09/Mar/2023:00:49:51 +0000] "POST /delete HTTP/1.1" 200 267 "http://<-TrimmedServerIP->:4235/" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/110.0"


 ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "app/main.py", line 97, in add
    status = await dqueue.add(url, quality, format, folder)
  File "/app/app/ytdl.py", line 276, in add
    return await self.__add_entry(entry, quality, format, folder, already)
  File "/app/app/ytdl.py", line 256, in __add_entry
    self.queue.put(Download(dldirectory, output, output_chapter, quality, format, self.config.YTDL_OPTIONS, dl))
  File "/app/app/ytdl.py", line 47, in __init__
    self.format = get_format(format, quality)
  File "/app/app/dl_formats.py", line 42, in get_format
    raise Exception(f"Unkown format {format}")
Exception: Unkown format DBZAbridged
```

**Comment by PikuZheng** [comment]
>INFO:aiohttp.access:<-TrimmedClientIP-> [09/Mar/2023:00:49:45 +0000] "GET /download/DBZAbridged/TeamFourStar%2FDragon%20Ball%20Z%20Abridged%EF%BC%9A%20Plan%20to%20Eradicate%20Christmas%20-%20Team%20Four%20Star%20(TFS).f140.m4a HTTP/1.1"

If you click the "download“ button (between "Retry" and "Source Link"), this event happened.
There may be other things to look out for in "Trimmed Unrelated Lines".

what browser are you using?
