### ISSUE TITLE
Empty queue on restart

### ISSUE THREAD

**Issue by ThisIsQasim** [alexta69/metube#258]
Seeing the following in the logs
```
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-3' coro=<DownloadQueue.__import_queue() done, defined at /app/app/ytdl.py:203> exception=TypeError("add() missing 1 required positional argument: 'custom_name_prefix'")>
Traceback (most recent call last):
  File "/app/app/ytdl.py", line 205, in __import_queue
    await self.add(v.url, v.quality, v.format, folder=v.folder)
TypeError: add() missing 1 required positional argument: 'custom_name_prefix'
```

**Comment by alexta69** [comment]
Thanks @ThisIsQasim !

**Comment by ThisIsQasim** [comment]
There is a new error
```
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-3' coro=<DownloadQueue.__import_queue() done, defined at /app/app/ytdl.py:203> exception=AttributeError("'DownloadInfo' object has no attribute 'custom_name_prefix'")>
Traceback (most recent call last):
  File "/app/app/ytdl.py", line 205, in __import_queue
    await self.add(v.url, v.quality, v.format, v.folder, v.custom_name_prefix)
AttributeError: 'DownloadInfo' object has no attribute 'custom_name_prefix'
```

**Comment by alexta69** [comment]
Doh! you're right of course.
