### ISSUE TITLE
Clear completed/selected does not work?

### ISSUE THREAD

**Issue by gerroon** [alexta69/metube#275]
Hi

I am trying to empty the downloaded list, so I select all in the list and click on the clear selected or clear completed but the list is never cleared up. Am I doing something wrong?

**Comment by PikuZheng** [comment]
osx+safari？

**Comment by gerroon** [comment]
I am using Chromium and Firefox on Windows.

**Comment by PikuZheng** [comment]
Maybe the debug console can provide more information, or your chromium version is too low (angularjs requires Chrome >= 55

**Comment by gerroon** [comment]
This is what I am getting in the console. My versions are all up to date like 114

```

ERROR TypeError: this[e].get(...) is undefined
    delById http://IP:PORT/main.2395ceb78eb7d32c.js:1
    delById http://IP:PORT/main.2395ceb78eb7d32c.js:1
    delByFilter http://IP:PORT/main.2395ceb78eb7d32c.js:1
    delSelectedDownloads http://IP:PORT/main.2395ceb78eb7d32c.js:1
    template http://IP:PORT/main.2395ceb78eb7d32c.js:1
    Of http://IP:PORT/main.2395ceb78eb7d32c.js:1
    a http://IP:PORT/main.2395ceb78eb7d32c.js:1
    Zh http://IP:PORT/main.2395ceb78eb7d32c.js:1
    invokeTask http://IP:PORT/polyfills.9883e537c98de6aa.js:1
    onInvokeTask http://IP:PORT/main.2395ceb78eb7d32c.js:1
    invokeTask http://IP:PORT/polyfills.9883e537c98de6aa.js:1
    runTask http://IP:PORT/polyfills.9883e537c98de6aa.js:1
    invokeTask http://IP:PORT/polyfills.9883e537c98de6aa.js:1
    S http://IP:PORT/polyfills.9883e537c98de6aa.js:1
    A http://IP:PORT/polyfills.9883e537c98de6aa.js:1
    L http://IP:PORT/polyfills.9883e537c98de6aa.js:1
main.2395ceb78eb7d32c.js:1:51555
    handleError http://IP:PORT/main.2395ceb78eb7d32c.js:1
    vf http://IP:PORT/main.2395ceb78eb7d32c.js:1
    Of http://IP:PORT/main.2395ceb78eb7d32c.js:1
    a http://IP:PORT/main.2395ceb78eb7d32c.js:1
    Zh http://IP:PORT/main.2395ceb78eb7d32c.js:1
    invokeTask http://IP:PORT/polyfills.9883e537c98de6aa.js:1
    onInvokeTask http://IP:PORT/main.2395ceb78eb7d32c.js:1
    invokeTask http://IP:PORT/polyfills.9883e537c98de6aa.js:1
    runTask http://IP:PORT/polyfills.9883e537c98de6aa.js:1
    invokeTask http://IP:PORT/polyfills.9883e537c98de6aa.js:1
    S http://IP:PORT/polyfills.9883e537c98de6aa.js:1
    A http://IP:PORT/polyfills.9883e537c98de6aa.js:1
    L http://IP:PORT/polyfills.9883e537c98de6aa.js:1
ERROR TypeError: this[e].get(...) is undefined
    delById http://IP:PORT/main.2395ceb78eb7d32c.js:1
    delById http://IP:PORT/main.2395ceb78eb7d32c.js:1
    delByFilter http://IP:PORT/main.2395ceb78eb7d32c.js:1
    clearCompletedDownloads http://IP:PORT/main.2395ceb78eb7d32c.js:1
    template http://IP:PORT/main.2395ceb78eb7d32c.js:1
    Of http://IP:PORT/main.2395ceb78eb7d32c.js:1
    a http://IP:PORT/main.2395ceb78eb7d32c.js:1
    Zh http://IP:PORT/main.2395ceb78eb7d32c.js:1
    invokeTask http://IP:PORT/polyfills.9883e537c98de6aa.js:1
    onInvokeTask http://IP:PORT/main.2395ceb78eb7d32c.js:1
    invokeTask http://IP:PORT/polyfills.9883e537c98de6aa.js:1
    runTask http://IP:PORT/polyfills.9883e537c98de6aa.js:1
    invokeTask http://IP:PORT/polyfills.9883e537c98de6aa.js:1
    S http://IP:PORT/polyfills.9883e537c98de6aa.js:1
    A http://IP:PORT/polyfills.9883e537c98de6aa.js:1
    L http://IP:PORT/polyfills.9883e537c98de6aa.js:1

```

**Comment by PikuZheng** [comment]
Try the browse in private mode of chrome please?

**Comment by gerroon** [comment]
still errors

in.2395ceb78eb7d32c.js:1 ERROR TypeError: Cannot set properties of undefined (setting 'deleting')
    at main.2395ceb78eb7d32c.js:1:481663
    at Array.forEach (<anonymous>)
    at t.delById (main.2395ceb78eb7d32c.js:1:481629)
    at t.delByFilter (main.2395ceb78eb7d32c.js:1:481789)
    at t.delSelectedDownloads (main.2395ceb78eb7d32c.js:1:554616)
    at main.2395ceb78eb7d32c.js:1:560841
    at Of (main.2395ceb78eb7d32c.js:1:76086)
    at a (main.2395ceb78eb7d32c.js:1:76253)
    at HTMLButtonElement.<anonymous> (main.2395ceb78eb7d32c.js:1:162375)
    at _.invokeTask (polyfills.9883e537c98de6aa.js:1:9356)
h

**Comment by PikuZheng** [comment]
sorry to hear that :(

**Comment by gerroon** [comment]
So is this a bug or what?

**Comment by PikuZheng** [comment]
It looks like you checked something, but the app can't get it.
I've never had this problem using windows and chrome all the time. I had thought some plugin was blocking something, but private mode wasn't.
If some firewalls between metube and windows, you may need to consider that.
Or try firefox?

**Comment by Nach0-Stallion** [comment]
Hi, just found i'm having the same issue, went to grab a video and decided to clear up the existing ones, the clear completed does nothing, tried Chrome and firefox on Windows 11 and in private mode, same issue.
no pop up blockers active on the up range, i restarted the docker and selected a few manually and clicked clear selected and they went, but trying selecting 10 and clearing seemed to bug it out and now wont clear even one, restarting the docker again didnt do anything (force updating was the same)
jumped onto my iPhone. Safari, same deal im afraid
happy to supply any logs or whatever maybe needed. cheers

**Comment by PikuZheng** [comment]
hi @Nach0-Stallion , do you use https?

**Comment by gerroon** [comment]
I do not use https myself, it is local lan for me.

**Comment by Nach0-Stallion** [comment]
> hi @Nach0-Stallion , do you use https?

Hi!
I access it on local lan, I deleted the 2 list files in the directory as I suspect maybe there was a file permissions issue? (Running in an Unraid docker) I have test downloaded a file and clear completed appears to be working again ☺️

**Comment by gerroon** [comment]
@Nach0-Stallion  where is the lists fiile? I do not see anything in the "downloads" share over my docker-compose setup.

**Comment by Nach0-Stallion** [comment]
I believe @gerroon its in a hidden folder in the default download directory, at least mine was a .metube folder

**Comment by gerroon** [comment]
@Nach0-Stallion  thanks, that seems to solve my issue too

**Comment by zenoven** [comment]
it should be a bug. 

the Map is strange, some key is a string hash, some is a string of URL, when cannot get the value in the Map, it fails

<img width="551" alt="image" src="https://github.com/alexta69/metube/assets/1305982/b3daaaf0-79e2-4f9c-ab3b-9d0518c3466d">


<img width="788" alt="image" src="https://github.com/alexta69/metube/assets/1305982/65d60388-8ccc-4019-a3be-625ec81a3e46">

**Comment by PikuZheng** [comment]
> some key is a string hash

it's the video id of youtube ( ppPd5GnNa2Y means https://www.youtube.com/watch?v=ppPd5GnNa2Y )
it will be a full url until the video id is obtained.

**Comment by zenoven** [comment]
> > some key is a string hash
> 
> it's the video id of youtube ( ppPd5GnNa2Y means https://www.youtube.com/watch?v=ppPd5GnNa2Y ) it will be a full url until the video id is obtained.

yes, but that's not the main point, I mean the value is undefined but the code wanna set deleting prop to undefined

<img width="430" alt="image" src="https://github.com/alexta69/metube/assets/1305982/20e85db8-e1c0-44ad-9425-7969bd3162f2">

**Comment by zenoven** [comment]
and in my case, whatever I choose(select only one item, or clear completed, etc.), the Map is size is 92

<img width="1110" alt="image" src="https://github.com/alexta69/metube/assets/1305982/48b7bd41-7769-4a41-b26a-1f3ed5fe5fcc">

**Comment by PikuZheng** [comment]
so. . . some items in the list don't have the 'format' attribute?

**Comment by alexta69** [comment]
Stale — the frontend has since been rewritten and the state storage replaced, so this specific failure mode no longer applies. Closing; please open a new issue if it recurs on a current version.
