### ISSUE TITLE
issue with tamil/emoji/other characters in youtube file names

### ISSUE THREAD

**Issue by jenishngl** [alexta69/metube#303]
Getting the below error in docker logs
`ERROR: unable to download video data: [Errno 22] Invalid argument: '/downloads/💥🕵10TH New Book TAMIL ⧸ இயல் - 1 முழுவதும் ⧸✍️ Line By Line Question ✍️⧸ Part-1💥🕵.f609.mp4.ytdl'`

when trying to download _**https://www.youtube.com/watch?v=h_0VjZ_IJRM**_

The tile contains Tamil language partly, but unsure why it fails to save

**Comment by PikuZheng** [comment]
mine fine
![image](https://github.com/alexta69/metube/assets/12579522/892d4dad-a87c-41c1-a66a-36df5e62c58f)

maybe filename is too long?

**Comment by jenishngl** [comment]
There is no way to change the filename for a download right. So I am not
sure how to check that.

This is running of docker container with a download path as directory
(mounted from USB drive mounted on raspberry pi)

How do I debug this further

--Jenish

**Comment by PikuZheng** [comment]
![image](https://github.com/alexta69/metube/assets/12579522/06c1f0a1-98e4-4077-a838-5d51d6aebae5)
or set the environment variable OUTPUT_TEMPLATE of the container as python string-format.
for example, %(title).50s (default is %(title).s) means cut title to 50 letters which is suitable for most file system

**Comment by jenishngl** [comment]
> ![image](https://user-images.githubusercontent.com/12579522/255812896-06c1f0a1-98e4-4077-a838-5d51d6aebae5.png) or set the environment variable OUTPUT_TEMPLATE of the container as python string-format. for example, %(title).50s (default is %(title).s) means cut title to 50 letters which is suitable for most file system

I have set the environment variable as  `OUTPUT_TEMPLATE=%(title).50s` but still getting below error. I can see that the title has been cut down to 50 characters

`ERROR: unable to download video data: [Errno 22] Invalid argument: '/downloads/💥🕵10TH New Book TAMIL ⧸ இயல் - 1 முழுவதும் ⧸✍️ Lin.f609.mp4.ytdl'`

**Comment by PikuZheng** [comment]
so...it doesn't look like a filename issue

**Comment by PikuZheng** [comment]
can you set `YTDL_OPTIONS={'verbose': True}` and post full debug log please

**Comment by jenishngl** [comment]
> can you set `YTDL_OPTIONS={'verbose': True}` and post full debug log please

I see the below now after adding YTDL_OPTIONS [here](https://github.com/jenishngl/youtubedl-material-docker-compose/blob/main/docker-compose.yaml)

```
INFO:aiohttp.access:172.16.16.10 [25/Jul/2023:10:55:53 +0000] "POST /add HTTP/1.1" 200 270 "https://youtube-dl.jjhome.in/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
ERROR: unable to download video data: [Errno 22] Invalid argument: '/downloads/💥🕵10TH New Book TAMIL ⧸ இயல் - 1 முழுவதும் ⧸✍️ Lin.f609.mp4.ytdl'
INFO:ytdl:waiting for item to download
```

**Comment by PikuZheng** [comment]
YTDL_OPTIONS is not properly configured, it should generate more logs

**Comment by PikuZheng** [comment]
https://github.com/jenishngl/youtubedl-material-docker-compose/blob/074370f1bb43b7701bd6f321ef126bf3fcbdd6d6/docker-compose.yaml#L12
```
....
      - YTDL_OPTIONS : '{"verbose": true}'
```
please

**Comment by jenishngl** [comment]
> https://github.com/jenishngl/youtubedl-material-docker-compose/blob/074370f1bb43b7701bd6f321ef126bf3fcbdd6d6/docker-compose.yaml#L12
> 
> ```
> ....
>       - YTDL_OPTIONS : '{"verbose": true}'
> ```
> 
> please

[Updated](https://github.com/jenishngl/youtubedl-material-docker-compose/blob/3ca73f6cdd43a0e6fd46ad881487078f70ca655e/docker-compose.yaml#L12). I dont think i am seeing much difference even now

```
INFO:aiohttp.access:172.16.16.10 [25/Jul/2023:14:15:21 +0000] "GET / HTTP/1.1" 304 215 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
INFO:aiohttp.access:172.16.16.10 [25/Jul/2023:14:15:21 +0000] "GET /socket.io/?EIO=4&transport=polling&t=OcDPuur HTTP/1.1" 200 288 "https://youtube-dl.jjhome.in/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
INFO:aiohttp.access:172.16.16.10 [25/Jul/2023:14:15:21 +0000] "POST /socket.io/?EIO=4&transport=polling&t=OcDPuvD&sid=6eoyN-CKrqCK4xZOAAAC HTTP/1.1" 200 280 "https://youtube-dl.jjhome.in/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
INFO:aiohttp.access:172.16.16.10 [25/Jul/2023:14:15:21 +0000] "GET /socket.io/?EIO=4&transport=polling&t=OcDPuvE&sid=6eoyN-CKrqCK4xZOAAAC HTTP/1.1" 200 1635 "https://youtube-dl.jjhome.in/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
INFO:aiohttp.access:172.16.16.10 [25/Jul/2023:14:15:21 +0000] "GET /socket.io/?EIO=4&transport=polling&t=OcDPuvm&sid=6eoyN-CKrqCK4xZOAAAC HTTP/1.1" 200 191 "https://youtube-dl.jjhome.in/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
INFO:aiohttp.access:172.16.16.10 [25/Jul/2023:14:15:21 +0000] "GET /favicon/favicon.ico HTTP/1.1" 200 252 "https://youtube-dl.jjhome.in/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
INFO:ytdl:adding https://www.youtube.com/watch?v=h_0VjZ_IJRM: quality='best' format='mp4' already=None folder=None custom_name_prefix=''
INFO:aiohttp.access:172.16.16.10 [25/Jul/2023:14:15:23 +0000] "POST /delete HTTP/1.1" 200 270 "https://youtube-dl.jjhome.in/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
INFO:ytdl:downloading 💥🕵10TH New Book TAMIL / இயல் - 1 முழுவதும் /✍️ Line By Line Question ✍️/ Part-1💥🕵
INFO:aiohttp.access:172.16.16.10 [25/Jul/2023:14:15:23 +0000] "POST /add HTTP/1.1" 200 270 "https://youtube-dl.jjhome.in/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
ERROR: unable to download video data: [Errno 22] Invalid argument: '/downloads/💥🕵10TH New Book TAMIL ⧸ இயல் - 1 முழுவதும் ⧸✍️ Lin.f609.mp4.ytdl'
INFO:ytdl:waiting for item to download
```

**Comment by PikuZheng** [comment]
![image](https://github.com/alexta69/metube/assets/12579522/03845bca-0401-4c0d-9716-4b2832819545)
not an array. sorry.

**Comment by jenishngl** [comment]
> ![image](https://user-images.githubusercontent.com/12579522/256054913-03845bca-0401-4c0d-9716-4b2832819545.png) not an array. sorry.

Seems now we are in the right direction

```
ERROR: unable to download video data: [Errno 22] Invalid argument: '/downloads/💥🕵10TH New Book TAMIL ⧸ இயல் - 1 முழுவதும் ⧸✍️ Line By Line Question ✍️⧸ Part-1💥🕵.f609.mp4.ytdl'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/yt_dlp/utils/_utils.py", line 663, in sanitize_open
    stream = locked_file(filename, open_mode, block=False).__enter__()
  File "/usr/local/lib/python3.8/site-packages/yt_dlp/utils/_utils.py", line 2036, in __init__
    self.f = os.fdopen(os.open(filename, flags, 0o666), mode, encoding=encoding)
OSError: [Errno 22] Invalid argument: '/downloads/💥🕵10TH New Book TAMIL ⧸ இயல் - 1 முழுவதும் ⧸✍️ Line By Line Question ✍️⧸ Part-1💥🕵.f609.mp4.ytdl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3345, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "/usr/local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3084, in dl
    return fd.download(name, new_info, subtitle)
  File "/usr/local/lib/python3.8/site-packages/yt_dlp/downloader/common.py", line 461, in download
    ret = self.real_download(filename, info_dict)
  File "/usr/local/lib/python3.8/site-packages/yt_dlp/downloader/hls.py", line 158, in real_download
    self._prepare_and_start_frag_download(ctx, info_dict)
  File "/usr/local/lib/python3.8/site-packages/yt_dlp/downloader/fragment.py", line 81, in _prepare_and_start_frag_download
    self._prepare_frag_download(ctx)
  File "/usr/local/lib/python3.8/site-packages/yt_dlp/downloader/fragment.py", line 217, in _prepare_frag_download
    self._write_ytdl_file(ctx)
  File "/usr/local/lib/python3.8/site-packages/yt_dlp/downloader/fragment.py", line 101, in _write_ytdl_file
    frag_index_stream, _ = self.sanitize_open(self.ytdl_filename(ctx['filename']), 'w')
  File "/usr/local/lib/python3.8/site-packages/yt_dlp/downloader/common.py", line 239, in wrapper
    for retry in RetryManager(self.params.get('file_access_retries', 3), error_callback, fd=self):
  File "/usr/local/lib/python3.8/site-packages/yt_dlp/utils/_utils.py", line 5634, in __iter__
    self.error_callback(self.error, self.attempt, self.retries)
  File "/usr/local/lib/python3.8/site-packages/yt_dlp/downloader/common.py", line 232, in error_callback
    return RetryManager.report_retry(
  File "/usr/local/lib/python3.8/site-packages/yt_dlp/utils/_utils.py", line 5642, in report_retry
    raise e
  File "/usr/local/lib/python3.8/site-packages/yt_dlp/downloader/common.py", line 241, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/yt_dlp/downloader/common.py", line 252, in sanitize_open
    f, filename = sanitize_open(filename, open_mode)
  File "/usr/local/lib/python3.8/site-packages/yt_dlp/utils/_utils.py", line 665, in sanitize_open
    stream = open(filename, open_mode)
OSError: [Errno 22] Invalid argument: '/downloads/💥🕵10TH New Book TAMIL ⧸ இயல் - 1 முழுவதும் ⧸✍️ Line By Line Question ✍️⧸ Part-1💥🕵.f609.mp4.ytdl'
```

**Comment by PikuZheng** [comment]
yes... It looks like the filesystem cannot accept this filename. is it (/data/komga/data/pendrive/youtube) vfat? mine is ext4 which works fine.

**Comment by jenishngl** [comment]
> yes... It looks like the filesystem cannot accept this filename. is it (/data/komga/data/pendrive/youtube) vfat? mine is ext4 which works fine.

yes, the usb drive was formated as fat32. Will try to change to ext4 then. I did not know that fat32 has this as a limitation

**Comment by PikuZheng** [comment]
It is limited by the operating system, file encoding eg CP437, if not properly extended.
Maybe exfat works in your case, it is supported by most windows, linux, android and osx
