### ISSUE TITLE
Getting this error: http.cookies.CookieError: Illegal key 'ys-api/dvr/entry/grid_upcoming'

### ISSUE THREAD

**Issue by daezerwin** [alexta69/metube#451]
I got this error, please see stack trace
`ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "aiohttp/_helpers.pyx", line 24, in aiohttp._helpers.reify.__get__
KeyError: 'cookies'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_urldispatcher.py", line 202, in handler_wrapper
    result = old_handler(request)
             ^^^^^^^^^^^^^^^^^^^^
  File "/app/app/main.py", line 199, in index
    if 'metube_theme' not in request.cookies:
                             ^^^^^^^^^^^^^^^
  File "aiohttp/_helpers.pyx", line 26, in aiohttp._helpers.reify.__get__
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_request.py", line 586, in cookies
    parsed = SimpleCookie(raw)
             ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/http/cookies.py", line 483, in __init__
    self.load(input)
  File "/usr/local/lib/python3.11/http/cookies.py", line 532, in load
    self.__parse_string(rawdata)
  File "/usr/local/lib/python3.11/http/cookies.py", line 596, in __parse_string
    self.__set(key, rval, cval)
  File "/usr/local/lib/python3.11/http/cookies.py", line 488, in __set
    M.set(key, real_value, coded_value)
  File "/usr/local/lib/python3.11/http/cookies.py", line 353, in set
    raise CookieError('Illegal key %r' % (key,))`

**Comment by PikuZheng** [comment]
Please try chrome's incognito mode
