### ISSUE TITLE
Caddy reverse proxy redirect loop

### ISSUE THREAD

**Issue by proess880** [alexta69/metube#460]
I want to deply metub behind Caddy (docker) as a reverse proxy. However i am unable to get it redirected properly.

### docker-compose.yml
```
services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - /media/share/Downloads:/downloads
      - ./data:/app/data
    environment:
      DOWNLOAD_DIR: /downloads
      STATE_DIR: /app/data/state
      TEMP_DIR: /app/data/temp
      URL_PREFIX: /metube

networks:
  proxy:
    external: true
```

### Caddyfile

```
https://services.mydomain.com {
	handle_path /metube/* {
		uri strip_prefix /metube  -> Also tried removing this line since **handle_path** does the same
		reverse_proxy http://metube:8081
	}
}
```

but i get an infinite redirect loop

![grafik](https://github.com/alexta69/metube/assets/173592847/4f65977c-49d1-4612-92b3-2e5be6217590)

And the logs of the container there are errors
```
INFO:aiohttp.access:172.26.0.2 [23/Jun/2024:05:37:47 +0000] "UNKNOWN / HTTP/1.0" 400 225 "-" "-"
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 350, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b'\x16\x03\x01\x01\x05\x01'
      ^
INFO:aiohttp.access:172.26.0.2 [23/Jun/2024:05:38:04 +0000] "UNKNOWN / HTTP/1.0" 400 225 "-" "-"
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 350, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b'\x16\x03\x01\x01\x05\x01'
      ^
INFO:aiohttp.access:172.26.0.2 [23/Jun/2024:05:38:07 +0000] "UNKNOWN / HTTP/1.0" 400 225 "-" "-"
INFO:aiohttp.access:172.26.0.2 [23/Jun/2024:05:38:15 +0000] "GET / HTTP/1.1" 302 185 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:127.0) Gecko/20100101 Firefox/127.0"
INFO:aiohttp.access:172.26.0.2 [23/Jun/2024:05:38:15 +0000] "GET / HTTP/1.1" 302 185 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:127.0) Gecko/20100101 Firefox/127.0"
INFO:aiohttp.access:172.26.0.2 [23/Jun/2024:05:38:15 +0000] "GET / HTTP/1.1" 302 185 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:127.0) Gecko/20100101 Firefox/127.0"
```

**Comment by PikuZheng** [comment]
URL_PREFIX: /metube
handle_path /metube/* {
		~uri strip_prefix /metube~

or

URL_PREFIX: /
handle_path /metube/* {
		uri strip_prefix /metube

**Comment by proess880** [comment]
it only worked after setting URL_PREFIX: / and accessing with https://services.mydomain.com/metube**/** (Notice the trailing slash is important) 

Caddyfile
```
https://services.mydomain.com {
	handle_path /metube/* {
		reverse_proxy http://metube:8081
	}
}
```
