### ISSUE TITLE
KeyError: 'id'  missing

### ISSUE THREAD

**Issue by mxia9416** [alexta69/metube#552]
When input a playlist url it will report KeyError 'id'', Metube works fine when input is a single video.
In addition, I tried the same playlist url with newest release of yt-dlp(win11) fork provided in readme and it worked fine, so I create an issue ticket here.
Log below:

```
DEBUG:ytdl:Processing as a video                                                 
ERROR:aiohttp.server:Error handling request                                      
Traceback (most recent call last):                                               
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 47
7, in _handle_request                                                            
    resp = await request_handler(request)                                                                              
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 559, in
 _handle                                                                         
    return await handler(request)                                                                                               
  File "/app/app/main.py", line 146, in add                                      
    status = await dqueue.add(url, quality, format, folder, custom_name_prefix, p
laylist_strict_mode, playlist_item_limit, auto_start)                                                
  File "/app/app/ytdl.py", line 337, in add                                      
    return await self.__add_entry(entry, quality, format, folder, custom_name_pre
fix, playlist_strict_mode, playlist_item_limit, auto_start, already)                      
  File "/app/app/ytdl.py", line 289, in __add_entry                              
    results.append(await self.__add_entry(etr, quality, format, folder, custom_na
me_prefix, playlist_strict_mode, playlist_item_limit, auto_start, already))      
  File "/app/app/ytdl.py", line 295, in __add_entry                              
    if not self.queue.exists(entry['id']):                                                            
KeyError: 'id'          
```

**Comment by PikuZheng** [comment]
Are you using the web ui to add the list or posting the list directly to the `/add` ?

**Comment by mxia9416** [comment]
I used webui, Metube itself is running on synology nas. 
For the test I mentioned, I just run ytdlp on my win11 pc use the same setting, which added a name template including 'id' field. The same setting works fine before with Metube.

> Are you using the web ui to add the list or posting the list directly to the `/add` ?

**Comment by PikuZheng** [comment]
yt-dlp command line has different behavior than embedded yt-dlp. 

to make it clear, are you means a playlist works fine with the old version of metube, but the new one doesn't work?  can you provide a link for test?

**Comment by mxia9416** [comment]
Yes, I set up Metube in my NAS like a years ago or so and it has been working without issue. I can't recall the exact version that cause this issue as I set up an auto update of the Metube docker container, I also don't use it daily, maybe every once in 2 months,  so I'm also surprised to find it stopped working today. My docker setting are below:
![image](https://github.com/user-attachments/assets/b2c76a18-9b1e-4855-866e-15ab2b017121)

Testing [list link](https://www.bilibili.com/video/BV1Ue4y1w7bk?spm_id_from=333.788.videopod.episodes&vd_source=16e3a0e67399ee2780b0af367b5c860e) will report error below:
![image](https://github.com/user-attachments/assets/0711be2b-04f8-4768-8bc7-c830d6881605)
The [individual ](https://www.bilibili.com/video/BV1X44y1v7hZ/?spm_id_from=333.999.0.0&vd_source=16e3a0e67399ee2780b0af367b5c860e)video in the list downloads fine.
![image](https://github.com/user-attachments/assets/2fd81471-9cc3-4b39-bd8e-791da7060c4e)

**Comment by PikuZheng** [comment]
啊 是b站

**Comment by mxia9416** [comment]
其实我是下P站的时候发现会报错，但感觉影响不好（
后来发现B站也不行，之前都是没问题的

**Comment by mxia9416** [comment]
试了一下，Strict Playlist mode可以把list里面的视频当成单独视频下载。
不过因为我的需求是输入list的url然后批量下载一个list里面的所有视频，这个方法可能并不适用。
我先用yt-dlp本体来下载，期待metube能修复这个问题 。

**Comment by PikuZheng** [comment]
@labmonkey could you please look into this issue? The 'id' attribute seems to be missing here https://github.com/alexta69/metube/blob/c4561dc9b33bec365ffeabdabc21497d02538df9/app/ytdl.py#L289

**Comment by PikuZheng** [comment]
> 试了一下，Strict Playlist mode可以把list里面的视频当成单独视频下载。 不过因为我的需求是输入list的url然后批量下载一个list里面的所有视频，这个方法可能并不适用。 我先用yt-dlp本体来下载，期待metube能修复这个问题 。

它会一个个全下载下来的，但是下载列表中只有一行。
或者你回退到这个版本试试 ghcr.io/alexta69/metube:2024-08-07

**Comment by mxia9416** [comment]
> metube:2024-08-07

Version _metube:2024-08-07_ has no issue and acts like before.
I'll keep on this version and pause auto-update until it's solved.
Thanks!

**Comment by denniseffing** [comment]
The issue is caused by the following line:
https://github.com/alexta69/metube/blob/d0a2de2acdfc71af4b144e16ee154b75dd56a1ef/app/ytdl.py#L286-L286

Some extractors do not return an `id` property when returning an entry of type `url` (e.g. the Patreon extractor). This worked fine before this line was added in 301ff92b.

**Comment by PikuZheng** [comment]
> Some extractors do not return an `id` property when returning an entry of type `url` (e.g. the Patreon extractor). This worked fine before this line was added in [301ff92](https://github.com/alexta69/metube/commit/301ff92b58a4f9a513481563f79789f289ecd5db).

I think @labmonkey 's commit cause this issue

> I am not sure what the correct fix is.

me too... I can't follow his train of thought.
This issue only occurs in non-youtube (i.e. no video id) situations. I think setting a default value might help?

**Comment by PikuZheng** [comment]
also strict mode failed after this commit

**Comment by Cinj216** [comment]
So is anything ever going to be done about this issue or is the creator going to stick to his guns of not reverting bad code?

**Comment by mxia9416** [comment]
I made a test container with the latest image (the one that added concurrent download mode) and deleted the line mentioned below. It worked for me to bypass the error of missing 'id' in my use case. I don't know if there will be other issue caused by deleting this line, but if anyone on  the same boat wants a temperary fix, this could be worth trying.
> [metube/app/ytdl.py](https://github.com/alexta69/metube/blob/d0a2de2acdfc71af4b144e16ee154b75dd56a1ef/app/ytdl.py#L286-L286)
> 
> Line 286 in [d0a2de2](/alexta69/metube/commit/d0a2de2acdfc71af4b144e16ee154b75dd56a1ef)
> 
>  etr["_type"] = "video" # Prevents video to be treated as url and lose below properties during processing
