### ISSUE TITLE
ERROR 500 - when using impersonate yt-dlp works directly but not via metube

### ISSUE THREAD

**Issue by admapop** [alexta69/metube#559]
YTDL_OPTIONS={"cookiefile":"/cookies/cookies.txt","verbose":"true","impersonate":"chrome"}

If I enter the docker container and execute yt-dlp directly with the cookiefile and impersonate, the download works.

When I try via the UI I get

```
INFO:ytdl:adding https://www.udemy.com/course/complete-react-developer-zero-to-mastery/learn/lecture/15090998#overview: quality='best' format='any' already=None folder=None custom_name_prefix='' playlist_strict_mode=False playlist_item_limit=0
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2024.12.23 from yt-dlp/yt-dlp [65cf46cdd] (pip) API
[debug] params: {'quiet': True, 'no_color': True, 'extract_flat': True, 'ignore_no_formats_error': True, 'noplaylist': False, 'paths': {'home': '/downloads', 'temp': '/downloads'}, 'cookiefile': '/cookies/cookies.txt', 'verbose': 'true', 'impersonate': 'chrome', 'color': 'no_color', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[debug] Python 3.11.11 (CPython aarch64 64bit) - Linux-6.8.0-1013-oracle-aarch64-with (OpenSSL 3.3.2 3 Sep 2024)
[debug] exe versions: ffmpeg 6.1.2 (setts), ffprobe 6.1.2
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.7.1, mutagen-1.47.0, requests-2.32.3, sqlite3-3.47.1, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 559, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/main.py", line 146, in add
    status = await dqueue.add(url, quality, format, folder, custom_name_prefix, playlist_strict_mode, playlist_item_limit, auto_start)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/ytdl.py", line 334, in add
    entry = await asyncio.get_running_loop().run_in_executor(None, self.__extract_info, url, playlist_strict_mode)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/ytdl.py", line 223, in __extract_info
    return yt_dlp.YoutubeDL(params={
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 742, in __init__
    if not self._impersonate_target_available(impersonate_target):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 4146, in _impersonate_target_available
    return any(
           ^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 4147, in <genexpr>
    rh.is_supported_target(target)
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/networking/impersonate.py", line 119, in is_supported_target
    assert isinstance(target, ImpersonateTarget)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
INFO:aiohttp.access:10.0.7.1 [27/Dec/2024:11:50:53 +0000] "POST /add HTTP/1.1" 500 346 "https://MYDOMAIN/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
INFO:ytdl:adding https://www.udemy.com/course/complete-react-developer-zero-to-mastery/learn/lecture/15090998#overview: quality='best' format='mp4' already=None folder=None custom_name_prefix='' playlist_strict_mode=False playlist_item_limit=0
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2024.12.23 from yt-dlp/yt-dlp [65cf46cdd] (pip) API
[debug] params: {'quiet': True, 'no_color': True, 'extract_flat': True, 'ignore_no_formats_error': True, 'noplaylist': False, 'paths': {'home': '/downloads', 'temp': '/downloads'}, 'cookiefile': '/cookies/cookies.txt', 'verbose': 'true', 'impersonate': 'safari', 'color': 'no_color', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[debug] Python 3.11.11 (CPython aarch64 64bit) - Linux-6.8.0-1013-oracle-aarch64-with (OpenSSL 3.3.2 3 Sep 2024)
[debug] exe versions: ffmpeg 6.1.2 (setts), ffprobe 6.1.2
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.7.1, mutagen-1.47.0, requests-2.32.3, sqlite3-3.47.1, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 559, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/main.py", line 146, in add
    status = await dqueue.add(url, quality, format, folder, custom_name_prefix, playlist_strict_mode, playlist_item_limit, auto_start)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/ytdl.py", line 334, in add
    entry = await asyncio.get_running_loop().run_in_executor(None, self.__extract_info, url, playlist_strict_mode)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/ytdl.py", line 223, in __extract_info
    return yt_dlp.YoutubeDL(params={
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 742, in __init__
    if not self._impersonate_target_available(impersonate_target):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 4146, in _impersonate_target_available
    return any(
           ^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 4147, in <genexpr>
    rh.is_supported_target(target)
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/networking/impersonate.py", line 119, in is_supported_target
    assert isinstance(target, ImpersonateTarget)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
INFO:aiohttp.access:10.0.7.1 [27/Dec/2024:11:50:57 +0000] "POST /add HTTP/1.1" 500 346 "https://MYDOMAIN/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
```

**Comment by PikuZheng** [comment]
Have you inspected into the container and installed the chrome component?

**Comment by admapop** [comment]
@PikuZheng how do you mean?

I've opened a sh in the container and was able to use yt-dlp directly with impersonate chrome, but didn't do much else. 

I also have a custom dockerfile to install some dependencies

**Comment by PikuZheng** [comment]
>[debug] yt-dlp version stable@2024.12.23 from yt-dlp/yt-dlp [65cf46cdd] (pip) API
[debug] params: {'quiet': True, 'no_color': True, 'extract_flat': True, 'ignore_no_formats_error': True, 'noplaylist': False, 'paths': {'home': '/downloads', 'temp': '/downloads'}, 'cookiefile': '/cookies/cookies.txt', 'verbose': 'true', 'impersonate': 'chrome', 'color': 'no_color', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[debug] Python 3.11.11 (CPython aarch64 64bit) - Linux-6.8.0-1013-oracle-aarch64-with (OpenSSL 3.3.2 3 Sep 2024)
[debug] exe versions: ffmpeg 6.1.2 (setts), ffprobe 6.1.2
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.7.1, mutagen-1.47.0, requests-2.32.3, sqlite3-3.47.1, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi

There is no impersonate named chrome, so I think something is missing in the runtime environment.
On the other hand, if the command line works fine in the same environment but the embedded one doesn't, it may be because the ytdl_options are incorrect. Can you write the command line that works properly so that we can determine the issue?

**Comment by admapop** [comment]
> > [debug] yt-dlp version stable@2024.12.23 from yt-dlp/yt-dlp [65cf46cdd] (pip) API
> > [debug] params: {'quiet': True, 'no_color': True, 'extract_flat': True, 'ignore_no_formats_error': True, 'noplaylist': False, 'paths': {'home': '/downloads', 'temp': '/downloads'}, 'cookiefile': '/cookies/cookies.txt', 'verbose': 'true', 'impersonate': 'chrome', 'color': 'no_color', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
> > [debug] Python 3.11.11 (CPython aarch64 64bit) - Linux-6.8.0-1013-oracle-aarch64-with (OpenSSL 3.3.2 3 Sep 2024)
> > [debug] exe versions: ffmpeg 6.1.2 (setts), ffprobe 6.1.2
> > [debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.7.1, mutagen-1.47.0, requests-2.32.3, sqlite3-3.47.1, urllib3-2.2.3, websockets-13.1
> > [debug] Proxy map: {}
> > [debug] Request Handlers: urllib, requests, websockets, curl_cffi
> 
> There is no impersonate named chrome, so I think something is missing in the runtime environment. On the other hand, if the command line works fine in the same environment but the embedded one doesn't, it may be because the ytdl_options are incorrect. Can you write the command line that works properly so that we can determine the issue?

You might be right about chrome not being right, i just saw in the code that there's a quick mapping between chrome and chrome-110.

This is the command I use that works

```bash
yt-dlp https://www.udemy.com/course/complete-react-developer-zero-to-mastery/learn/lecture/14754858#overview --cookies /cookies/cookies.txt --impersonate="chrome-110"
```

My YTDL options are like this
```
YTDL_OPTIONS={"cookiefile":"/cookies/cookies.txt","verbose":"true","impersonate":"chrome"}
```
And loaded in the docker compose via env var
```
    environment:
      - SERVICE_FQDN_METUBE_8081
      - UID=1000
      - GID=1000
      - YTDL_OPTIONS
 ```

**Comment by PikuZheng** [comment]
>YTDL_OPTIONS={"cookiefile":"/cookies/cookies.txt","verbose":"true","impersonate":"chrome"}

according to https://github.com/yt-dlp/yt-dlp/blob/0b6b7742c2e7f2a1fcb0b54ef3dd484bab404b3f/yt_dlp/YoutubeDL.py#L422 
`impersonate` should be an ImpersonateTarget object. metube processes ytdl_options as json, which does not support this

or you need to modify YoutubeDL.py so that json is converted to class object

**Comment by admapop** [comment]
> > YTDL_OPTIONS={"cookiefile":"/cookies/cookies.txt","verbose":"true","impersonate":"chrome"}
> 
> according to https://github.com/yt-dlp/yt-dlp/blob/0b6b7742c2e7f2a1fcb0b54ef3dd484bab404b3f/yt_dlp/YoutubeDL.py#L422 `impersonate` should be an ImpersonateTarget object. metube processes ytdl_options as json, which does not support this
> 
> or you need to modify YoutubeDL.py so that json is converted to class object

Good point. I made a quick PR to create the ImpersonateTarget object if the impersonate property exists

https://github.com/alexta69/metube/pull/560

**Comment by PikuZheng** [comment]
nice job

**Comment by PikuZheng** [comment]
Depending on your pr, should ytdl_options be written as ` "impersonate": "chrome-110:windows-10"` ?

**Comment by admapop** [comment]
> Depending on your pr, should ytdl_options be written as ` "impersonate": "chrome-110:windows-10"` ?

I'm not sure? When running the command directly I can get away with using chrome-110 without specifying OS.

**Comment by PikuZheng** [comment]
What I tried
```
YTDL_OPTIONS={ 
  "impersonate": {
    "client": "chrome",
    "version": "110",
    "os": "windows",
    "os_version": "10"
  }
}
```
main.py
```
from yt_dlp.networking.impersonate import ImpersonateTarget
class Config:
    def __init__(self):
        ................
        if impersonate_data := self.YTDL_OPTIONS.get("impersonate"):
            self.YTDL_OPTIONS["impersonate"] = ImpersonateTarget(**impersonate_data)
```

**Comment by ctschach** [comment]
I'm also running into this issue. If I just provide a string for impersonate, I see the exact same "AssertionError" that was mentioned in the beginning.

Now that the pull request has been merged, I was hoping that this will work. So I also tried:

`    "impersonate": { "client": "chrome", "version": "110", "os": windows, "os_version": "10" },
`

in my ytdl-options.json and I'm no getting a different error:

```
metube    |   File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
metube    |     result = self.fn(*self.args, **self.kwargs)
metube    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
metube    |   File "/app/app/ytdl.py", line 232, in __extract_info
metube    |     **({'impersonate': yt_dlp.networking.impersonate.ImpersonateTarget.from_str(self.config.YTDL_OPTIONS['impersonate'])} if 'impersonate' in self.config.YTDL_OPTIONS else {}),
metube    |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
metube    |   File "/usr/local/lib/python3.11/site-packages/yt_dlp/networking/impersonate.py", line 55, in from_str
metube    |     mobj = re.fullmatch(r'(?:(?P<client>[^:-]+)(?:-(?P<version>[^:-]+))?)?(?::(?:(?P<os>[^:-]+)(?:-(?P<os_version>[^:-]+))?)?)?', target)
metube    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
metube    |   File "/usr/local/lib/python3.11/re/__init__.py", line 171, in fullmatch
metube    |     return _compile(pattern, flags).fullmatch(string)
metube    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
metube    | TypeError: expected string or bytes-like object, got 'dict'
```

Looks like a dict is not expected.

So what's the correct syntax to provide the impersonate parameters?

**Comment by ctschach** [comment]
As I mentioned before, this gives the same AssertionError that was already shown:

```
metube    | [debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
metube    | [debug] yt-dlp version stable@2024.12.23 from yt-dlp/yt-dlp [65cf46cdd] (pip) API
metube    | [debug] params: {'quiet': True, 'no_color': True, 'extract_flat': True, 'ignore_no_formats_error': True, 'noplaylist': False, 'paths': {'home': '/inbox', 'temp': '/downloads'}, 'impersonate': 'chrome-110', 'cookiefile': '/cookies/cookies.txt', 'verbose': True, 'overwrites': True, 'updatetime': False, 'writedescription': True, 'writethumbnail': True, 'writeinfojson': True, 'clean_infojson': True, 'writesubtitles': True, 'subtitleslangs': ['all', '-live_chat'], 'format': 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', 'exec': 'cp -p %(filepath)q %(filepath)q.h264.mp4', 'postprocessors': [{'key': 'Exec', 'exec_cmd': 'sh /savecopy.sh {}', 'when': 'post_process'}, {'key': 'FFmpegEmbedSubtitle', 'already_have_subtitle': False}, {'key': 'FFmpegMetadata', 'add_chapters': True, 'add_metadata': True, 'add_infojson': 'if_exists'}, {'key': 'EmbedThumbnail'}, {'key': 'FFmpegCopyStream'}], 'postprocessor_args': {'offmerger': ['-metadata:s', 'title=', '-metadata:s', 'handler_name='], 'copystream': ['-vaapi_device', '/dev/dri/renderD128', '-vf', 'format=nv12,hwupload', '-c:v', 'hevc_vaapi', '-crf', '20', '-tag:v', 'hvc1', '-c:a', 'copy']}, 'color': 'no_color', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
metube    | [debug] Python 3.11.11 (CPython x86_64 64bit) - Linux-5.15.0-130-generic-x86_64-with (OpenSSL 3.3.2 3 Sep 2024)
metube    | [debug] exe versions: ffmpeg 6.1.2 (setts), ffprobe 6.1.2
metube    | [debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.7.1, mutagen-1.47.0, requests-2.32.3, sqlite3-3.47.1, urllib3-2.2.3, websockets-13.1
metube    | [debug] Proxy map: {}
metube    | [debug] Request Handlers: urllib, requests, websockets, curl_cffi
metube    | ERROR:aiohttp.server:Error handling request
metube    | Traceback (most recent call last):
metube    |   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request
metube    |     resp = await request_handler(request)
metube    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
metube    |   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 559, in _handle
metube    |     return await handler(request)
metube    |            ^^^^^^^^^^^^^^^^^^^^^^
metube    |   File "/app/app/main.py", line 146, in add
metube    |     status = await dqueue.add(url, quality, format, folder, custom_name_prefix, playlist_strict_mode, playlist_item_limit, auto_start)
metube    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
metube    |   File "/app/app/ytdl.py", line 337, in add
metube    |     entry = await asyncio.get_running_loop().run_in_executor(None, self.__extract_info, url, playlist_strict_mode)
metube    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
metube    |   File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
metube    |     result = self.fn(*self.args, **self.kwargs)
metube    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
metube    |   File "/app/app/ytdl.py", line 225, in __extract_info
metube    |     return yt_dlp.YoutubeDL(params={
metube    |            ^^^^^^^^^^^^^^^^^^^^^^^^^
metube    |   File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 742, in __init__
metube    |     if not self._impersonate_target_available(impersonate_target):
metube    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
metube    |   File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 4146, in _impersonate_target_available
metube    |     return any(
metube    |            ^^^^
metube    |   File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 4147, in <genexpr>
metube    |     rh.is_supported_target(target)
metube    |   File "/usr/local/lib/python3.11/site-packages/yt_dlp/networking/impersonate.py", line 119, in is_supported_target
metube    |     assert isinstance(target, ImpersonateTarget)
metube    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
metube    | AssertionError
```

**Comment by PikuZheng** [comment]
I believe using a dictionary is a good idea, especially since curl-impersonate has been updated to provide more OS options

**Comment by admapop** [comment]
I'll give it a look maybe today

**Comment by Kribensisis** [comment]
Just checking if this was ever solved? I run MeTube in Docker and found that while I can install yt-dlp locally with curl_cffi and then do something like `yt-dlp --extractor-args "generic:impersonate" https://www.website.com/videos/download/`, that doesn't work from inside the MeTube container. 

I don't know how to use these curl_cffi arguments with MeTube and assume they don't work because the version in MeTube doesn't have the library. 

From an end user point of view, is there anything I can do?

**Comment by Kribensisis** [comment]
@admapop do you know? How can I send custom arguments to MeTube?

**Comment by you-cant-see-me** [comment]
Also, the prior fix only concerned the first step of getting metadata, the actual download is still broken, will add this too shortly

**Comment by janusn** [comment]
@alexta69 
Could you tell me what is a working value of `impersonate`?
I have tried to add the following argument onto `compose.yaml`:
```
environment:
      - 'YTDL_OPTIONS={ "impersonate": "chrome" }'
```
which I was following the suggestion of the error from the WebUI:
![Image](https://github.com/user-attachments/assets/9620494f-8721-4414-8750-00176044ac64)
The result of `yt-dlp --list-impersonate-targets` inside the container with a freshly downloaded image:
```
$ yt-dlp --list-impersonate-targets
[info] Available impersonate targets
Client    OS   Source
--------------------------------------------
Edge      -    curl_cffi (unavailable)
Firefox   -    curl_cffi>=0.10 (unavailable)
Safari    -    curl_cffi (unavailable)
Chrome    -    curl_cffi (unavailable)
```

**Comment by janusn** [comment]
@PikuZheng 

Thanks for your help. I have made a `Dockfile` that builds the image automatically when `metube` updates.
```
$ cat Dockerfile
FROM --platform=linux/amd64 "ghcr.io/alexta69/metube:latest" AS curl_cffi
RUN pip install --no-cache-dir curl_cffi

FROM ghcr.io/alexta69/metube:latest
COPY --from=curl_cffi /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages
```

Please feel free to include it in the document to help people install it. 😁
