### ISSUE TITLE
Plugins and bookmarklets not working in new version

### ISSUE THREAD

**Issue by nanocortex** [alexta69/metube#85]
After recent upgrade all bookmarklets and plugins stopped working.

Correct me if I'm wrong but it's probably caused by `format` parameter being required, but defaulting to `best` instead of `any`?

```
INFO:ytdl:adding https://www.youtube.com/watch?v=wZ3nkgCAMn4

ERROR:aiohttp.server:Error handling request

Traceback (most recent call last):

  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 430, in _handle_request

    resp = await request_handler(request)

  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 504, in _handle

    resp = await handler(request)

  File "app/main.py", line 80, in add

    status = await dqueue.add(url, quality, format)

  File "/app/app/ytdl.py", line 184, in add

    return await self.__add_entry(entry, quality, format, already)

  File "/app/app/ytdl.py", line 163, in __add_entry

    self.queue[entry['id']] = Download(dldirectory, self.config.OUTPUT_TEMPLATE, quality, format, self.config.YTDL_OPTIONS, dl)

  File "/app/app/ytdl.py", line 40, in __init__

    self.format = get_format(format, quality)

  File "/app/app/dl_formats.py", line 35, in get_format

    raise Exception(f"Unkown format {format}")

Exception: Unkown format best

```

**Comment by alexta69** [comment]
Fixed now, can you please check again with the new version (once it finishes building)?

**Comment by nanocortex** [comment]
I confirm that it works now. Thank you!
